services:
  server:
    build:
      context: .
    ports:
      - "8081:8080" # Cambiamos el puerto 8080 externo a 8081
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"  # Máquina 5433 → contenedor 5432
    environment:
      POSTGRES_DB: examen2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
